# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

In [3]:
import numpy as np

matriz = np.zeros((3, 3)) #criei um objeto multidimensional
vetor = np.array([10, 20, 30]) #criei um objeto unidimensional
matriz[1] = vetor #inseri o objeto unidimensional no index 1 do objeto multidimensional

print (f"Sim! Um objeto composto multidimensional pode recerber um objeto composto unidimensional.")
print (matriz)

Sim! Um objeto composto multidimensional pode recerber um objeto composto unidimensional.
[[ 0.  0.  0.]
 [10. 20. 30.]
 [ 0.  0.  0.]]


## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [5]:
genes = ['BRCA1','TP53', 'EGFR', 'CFTR', 'APOE']

gene1 = [
    len(genes[0]),                 
    genes[0][:2],                  
    genes[0].lower().count('a'),  
    "hu" in genes[0].lower()      
]

gene2 = [
    len(genes[1]),                 
    genes[1][:2],                  
    genes[1].lower().count('a'),  
    "hu" in genes[1].lower()      
]

gene3 = [
    len(genes[2]),                 
    genes[2][:2],                  
    genes[2].lower().count('a'),  
    "hu" in genes[2].lower()      
]

gene4 = [
    len(genes[3]),                 
    genes[3][:2],                  
    genes[3].lower().count('a'),  
    "hu" in genes[3].lower()      
]

gene5 = [
    len(genes[4]),                 
    genes[4][:2],                  
    genes[4].lower().count('a'),  
    "hu" in genes[4].lower()      
]

obj_composto = [gene1, gene2, gene3, gene4, gene5]
obj_composto

[[5, 'BR', 1, False],
 [4, 'TP', 0, False],
 [4, 'EG', 0, False],
 [4, 'CF', 0, False],
 [4, 'AP', 1, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [8]:
array = np.array(obj_composto)
print(array)

[['5' 'BR' '1' 'False']
 ['4' 'TP' '0' 'False']
 ['4' 'EG' '0' 'False']
 ['4' 'CF' '0' 'False']
 ['4' 'AP' '1' 'False']]


## 4 – Recupere todos os itens do terceiro gene.

In [10]:
print(array[2])

['4' 'EG' '0' 'False']


## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [12]:
print(array[:,3]) #retorna a ultima coluna (se tem caracter 'hu') de todos os elementos da lista

['False' 'False' 'False' 'False' 'False']


## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [ ]:
print (array[[1,3], 1:3]) #linha e coluna. Linhas 2 e 4, index 1 e 3. Colunas 2 à 4, index 1 à 3

[['TP' '0']
 ['CF' '0']]


## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [14]:
import pandas as pd 
dict_3 = {
    genes[0]: gene1,
    genes[1]: gene2,
    genes[2]: gene3,
    genes[3]: gene4,
    genes[4]: gene5
}

df = pd.DataFrame(dict_3).transpose()
df.columns = ["Tamanho", "Inicio", "Qtd_a", "Tem_hu"]
print(df)

      Tamanho Inicio Qtd_a Tem_hu
BRCA1       5     BR     1  False
TP53        4     TP     0  False
EGFR        4     EG     0  False
CFTR        4     CF     0  False
APOE        4     AP     1  False


## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [32]:
print (df[["Tamanho", "Qtd_a"]])

      Tamanho Qtd_a
BRCA1       5     1
TP53        4     0
EGFR        4     0
CFTR        4     0
APOE        4     1


## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [35]:
print (df.loc[['BRCA1',  'EGFR'], 'Tem_hu'])

BRCA1    False
EGFR     False
Name: Tem_hu, dtype: object


## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [23]:
df_data = pd.read_csv("./data.csv")

dict_data = {
    'N_Entrada': len(df_data),
    'Classes_colunas': list(df_data.dtypes),
    'N_classe': df_data.dtypes.value_counts().tolist(),
    'Media': [
        df_data.iloc[:, 0].mean(), 
        df_data.iloc[:, 3].mean(), 
        df_data.iloc[:, 8].mean()        
    ],
    'Desvio_padrao': [
        df_data.iloc[:,0].std(), 
        df_data.iloc[:, 3].std(), 
        df_data.iloc[:, 8].std()
    ],
    'terceiro_quartil': [
        df_data.iloc[:, 0].quantile(0.75), 
        df_data.iloc[:, 3].quantile(0.75), 
        df_data.iloc[:, 8].quantile(0.75)
    ]

}

dict_data

{'N_Entrada': 36634,
 'Classes_colunas': [dtype('int64'),
  <StringDtype(storage='python', na_value=nan)>,
  <StringDtype(storage='python', na_value=nan)>,
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('int64'),
  dtype('float64'),
  dtype('float64'),
  <StringDtype(storage='python', na_value=nan)>,
  <StringDtype(storage='python', na_value=nan)>,
  dtype('int64')],
 'N_classe': [11, 4, 3],
 'Media': [np.float64(548661.9371894961),
  np.float64(731478.0068460993),
  np.float64(2571004.0973420865)],
 'Desvio_padrao': [np.float64(259912.9264939009),
  np.float64(17523003.588415083),
  np.float64(20367766.569178067)],
 'terceiro_quartil': [np.float64(774252.0),
  np.float64(0.0),
  np.float64(1128871.1824999999)]}