# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [35]:
a = 2.0 + 3.0/5.0
b = (a + 10.2) - 5.0 * 2.0
c= a / b + 33.8
d = a / (b + c)
e = d * 2

print (a)
print (b)
print (c)
print (d)
print (e)


2.6
2.799999999999999
34.72857142857143
0.0692805481537876
0.1385610963075752


## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [36]:
lista_a = [2.0, 3.0, 5.0] + [10, 20, 30]
lista_b = lista_a * 2
lista_c = lista_a + lista_b
lista_d = lista_a / (lista_b * lista_c) #não é possível dividir ou multiplicar duas listas

print (lista_a)
print (lista_b)
print (lista_c)
print (lista_d)

TypeError: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [37]:
lista_1 = [a, b, c, d, e]
lista_2 = [a**0.5, b**0.5, c**0.5, d**0.5, e**0.5]
lista_3 = lista_1 + lista_2
lista_3

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752,
 1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [38]:
import numpy as np 
lista_dupl = lista_3 * 2
array_dupl = np.array(lista_dupl).reshape(5,4)
print (array_dupl)


[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]]


## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [39]:
medias = array_dupl.mean(axis=0)
lista_medias = medias.tolist()
print(lista_medias)

[7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]


## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [40]:
total_elementos = array_dupl.shape[0] * array_dupl.shape[1]
print (total_elementos)

novo_array = np.append(array_dupl, [lista_medias], axis=0)
print(novo_array)

20
[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   1.61245155  1.67332005  5.89309523]
 [ 0.26321198  0.37223796  2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   1.61245155]
 [ 1.67332005  5.89309523  0.26321198  0.37223796]
 [ 7.88073291  2.14941306  7.88073291  2.14941306]]


## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [41]:
import pandas as pd 

novo_array.reshape(6,4)
df = pd.DataFrame(novo_array)
df = df.round(3)
print (df)


        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [42]:
media_linhas = df.mean(axis=1)
df["Media_linha"] = media_linhas.round(3)
print(df)

        0      1       2      3  Media_linha
0   2.600  2.800  34.729  0.069       10.050
1   0.139  1.612   1.673  5.893        2.329
2   0.263  0.372   2.600  2.800        1.509
3  34.729  0.069   0.139  1.612        9.137
4   1.673  5.893   0.263  0.372        2.050
5   7.881  2.149   7.881  2.149        5.015


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [43]:
print(df.iloc[:, -1].describe()) #ultima coluna

df_t = df.transpose() #linha virou coluna, e coluna virou linha
print(df_t.iloc[:, -1].describe()) #ultima coluna (que era a ultima linha)


count     6.000000
mean      5.015000
std       3.758722
min       1.509000
25%       2.119750
50%       3.672000
75%       8.106500
max      10.050000
Name: Media_linha, dtype: float64
count    5.000
mean     5.015
std      2.866
min      2.149
25%      2.149
50%      5.015
75%      7.881
max      7.881
Name: 5, dtype: float64


## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [44]:
df.columns = [1, 2, 3, 4, "Médias"]
df.index = [0, 1, 2, 3, 4, "Médias"]
media_media = df.iloc[-1, -1]
print (f"A média das médias (indice: [4, 5]) é: {media_media}")
print (df)

A média das médias (indice: [4, 5]) é: 5.015
             1      2       3      4  Médias
0        2.600  2.800  34.729  0.069  10.050
1        0.139  1.612   1.673  5.893   2.329
2        0.263  0.372   2.600  2.800   1.509
3       34.729  0.069   0.139  1.612   9.137
4        1.673  5.893   0.263  0.372   2.050
Médias   7.881  2.149   7.881  2.149   5.015


In [45]:
df.to_csv('df_atv7.csv')
