# Exercício:

## 01 – Cite três vantagens do uso das funções e duas características que toda função deva ter?

R.: O uso das funções permite a reutilização do código, além de deixar a organização e a manutenção mais fácil. Uma função deve ter um identificador, que possibilita sua chamada ao longo do script e o corpo, que define o que essa função fará.

## Responda a pergunta do exercício 2 da aula 10, usando funções:<br>
Instancie um objeto da classe NumPy array, contendo 5 valores quantitativos randômicos normalmente distribuídos, com média 10 e desvio padrão 3.<br><br>
Quantos e quais são os valores superiores a 10?

## 02 – Descreva o racional da sua resposta:

R.: 1 - Criei uma função 'analisar_valores' <br>
2 - Instanciei uma variável da classe array, gerando números aleatórios com distribuição normal ("random.normal"), onde a media é 10 ("loc"), o desvio padrão é 3 ("scale") e o tamanho é 5 ("size").<br>
3 - Instanciei uma variável para armazenar os valores maiores que 10, utilizei o operador lógico (>) para verificar essa condição.<br>
4 - Instanciei uma variável para armazenar o tamanho da última variável, ou seja, ver quantos números maiores que  10 existem.<br>
5 - Printei os resultados.

## 03 – Desenhe o fluxograma da resposta:

<img src="./img/exercicio12_atv3.jpeg" width="400" />

## 04 – Escreva o programa em Python:

In [1]:
import numpy as np

In [2]:
def analisar_valores():
    
    array = np.random.normal(loc=10, scale=3, size=5)
    maiores_que_10 = array[array > 10]
    quantidade = len(maiores_que_10)
    
    print("Array gerado:", array)
    print("Valores > 10:", maiores_que_10)
    print("Quantidade:", quantidade)
    
    return array, maiores_que_10, quantidade

analisar_valores()


Array gerado: [ 9.77137286 11.78532484 12.25762209 11.08929027  9.38477232]
Valores > 10: [11.78532484 12.25762209 11.08929027]
Quantidade: 3


(array([ 9.77137286, 11.78532484, 12.25762209, 11.08929027,  9.38477232]),
 array([11.78532484, 12.25762209, 11.08929027]),
 3)

## 05 – Seria possível, com o racional proposto, saber quantos e quais valores são superiores a 20? Porque?

R: Sim. Alterando o valor da comparação utilizado na função.

In [3]:
def analisar_valores_20():
    
    array = np.random.normal(loc=10, scale=3, size=5)
    maiores_que_20 = array[array > 20]
    quantidade = len(maiores_que_20)
    
    print("Array gerado:", array)
    print("Valores > 20:", maiores_que_20)
    print("Quantidade:", quantidade)
    
    return array, maiores_que_20, quantidade

analisar_valores_20()

Array gerado: [10.82532842  8.96744375  9.02668051  7.34381139 11.42017846]
Valores > 20: []
Quantidade: 0


(array([10.82532842,  8.96744375,  9.02668051,  7.34381139, 11.42017846]),
 array([], dtype=float64),
 0)

## Desenvolva um programa de computador que retorne a média de um conjunto de valores.

## 06 – Descreva o racional da sua resposta:

R.: 1 - Nomeei uma função<br>
2 - Instanciei uma variável da classe lista<br>
3 - Utilizando o numpy gerei randomicamente 5 números e armazenei nessa lista<br>
4 - Instanciei uma variável para calcular a média, ela recebe a soma dos valores da lista e divide pelo seu tamanho<br>
5 - Printei a saída

## 07 – Desenhe o fluxograma da resposta:

<img src="./img/exercicio12_atv7.jpeg" width="400" />

## 07 – Escreva o programa em Python:

In [4]:
def media():
    lista = np.random.normal(size=5).tolist()
    media = sum(lista) / len(lista)
    print (media)
    
media()


0.5198030328688196


## 09 – Desenvolva um programa de computador que retorne a divisão de dois objetos simples. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [5]:
def dividir_simples(a, b):
    print("Objeto A:")
    print("Valor:", a)
    print("Classe:", type(a))
    
    print("\nObjeto B:")
    print("Valor:", b)
    print("Classe:", type(b))
    
    try:
        resultado = a / b
        print("\nResultado da divisão:", resultado)
        print("Classe do resultado:", type(resultado))
    except Exception as e:
        print("\nErro na divisão:", e)

dividir_simples(10, 30)


Objeto A:
Valor: 10
Classe: <class 'int'>

Objeto B:
Valor: 30
Classe: <class 'int'>

Resultado da divisão: 0.3333333333333333
Classe do resultado: <class 'float'>


## 10 – Desenvolva um programa de computador que retorne a divisão de dois objetos compostos. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [6]:
def dividir_composto(lista_a, lista_b):
    print("Objeto 1:")
    print("Valor:", lista_a)
    print("Classe:", type(lista_a))
    
    print("\nObjeto 2:")
    print("Valor:", lista_b)
    print("Classe:", type(lista_b))

    resultado = []
    
    try:
        for i in range(len(lista_a)):
            resultado.append(lista_a[i]/lista_b[i])
            
        print("\nResultado da divisão:", resultado)
        print("Classe do resultado:", type(resultado))
    except Exception as e:
        print("\nErro na divisão:", e)

dividir_composto([10, 30, 40, 12], [2, 60,10,5])

Objeto 1:
Valor: [10, 30, 40, 12]
Classe: <class 'list'>

Objeto 2:
Valor: [2, 60, 10, 5]
Classe: <class 'list'>

Resultado da divisão: [5.0, 0.5, 4.0, 2.4]
Classe do resultado: <class 'list'>
